version: "3"
services:
  backend:
    build: /
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
